[project]
name = "pyvestaboard"
version = "0.0.1"
authors = [
  { name="Travis Johnson", email="travis.jo@programati.ca" },
]
description = "Vestaboard command line utility"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
	"Programming Language :: Python :: 3",
	"Operating System :: OS Independent",
]
license = "BSD-3-Clause-Attribution"
license-files = ["LICEN[CS]E*"]

dependencies = [
	"click==8.3.1",
	"requests==2.32.5",
	"regex==2026.1.15"
]

[project.urls]
Homepage = "https://github.com/travisjo/pyvestaboard"
Issues = "https://github.com/travisjo/pyvestaboard/issues"

[project.scripts]
vb = "pyvestaboard.local_client:cli"